### ISSUE TITLE
Filter with operator `contains` is broken

### ISSUE THREAD

**Issue by balajimanoharan** [yahoo/navi#244]
Filter with operator `contains` is broken 
Looks like the app is missing ember-tag-input.

![screen shot 2018-10-22 at 11 30 41 am](https://user-images.githubusercontent.com/2703389/47305083-fd64b080-d5ed-11e8-84e2-16f3c6792d2f.png)

**Comment by daniellevinson** [comment]
Couldn't reproduce, this has probably been fixed already. Will reopen if necessary
