### ISSUE TITLE
UX issue when filtering in dimension dropdown

### ISSUE THREAD

**Issue by jacobtolar** [yahoo/navi#344]
When I type to filter on a dimension name, the combobox list is filtered by what I've typed.

After I select what I want, the search text doesn't go away but the combobox filter is dropped and everything is shown.

**Comment by jacobtolar** [comment]
Example: 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/1390277/54789949-561e9080-4c02-11e9-8bc0-0c1aa8781738.gif)

**Comment by jacobtolar** [comment]
@Alex-Aralis Are you sure? I'm not sure #351 fixes this issue. I just rebuilt the demo app locally with your changes ( see https://github.com/yahoo/navi/pull/355 ) and the behavior I described above persists.

**Comment by cythrawll** [comment]
Yes I believe this is a different issue than what we were fixing in the other branch.

This bug I believe is an upstream bug with the dropdown component we're using. We need to update the component library, we're working on a much larger ember upgrade so we can tackles this.

**Comment by jacobtolar** [comment]
Ok.

Can this be reopened if it was closed incorrectly? Or is there a different issue I should follow?
