### ISSUE TITLE
Allow series selector to expand beyond edit panel

### ISSUE THREAD

**Issue by jkusa** [yahoo/navi#37]
The series selector can seem a little cramped. We should let it overflow outside the config pane.

TODO:
- [x] Allow series selector to expand
- [ ] Investigate column reorder test utility
- [ ] Investigate broken test

<img width="384" alt="screen shot 2018-02-22 at 3 53 18 pm" src="https://user-images.githubusercontent.com/2983409/36566283-a5a29bdc-17e8-11e8-836f-639ae4b30aa7.png">

**Comment by Alex-Aralis** [comment]
fixed in #225

**Comment by balajimanoharan** [comment]
Getting rid of the component soon. https://github.com/yahoo/navi/issues/513
