### ISSUE TITLE
The custom date range picker apply button is too small

### ISSUE THREAD

**Issue by kevinhinterlong** [yahoo/navi#543]
**Describe the bug**
The custom date range picker's apply button is not sized correctly

**To Reproduce**
1. Go to https://yahoo.github.io/navi/#/reports/1/view
2. Click on Last 7 days
3. Click on Custom range in the dropdown
4. The apply button is too small

**Expected behavior**
Should be the same size as the Reset button

**Screenshots**
<img width="647" alt="Screen Shot 2019-10-03 at 3 01 24 PM" src="https://user-images.githubusercontent.com/12093492/66160135-1bed6d00-e5ef-11e9-8459-696e99db7084.png">

**Desktop:**
 - OS: macOS
 - Browser: Google Chrome
 - Version: 77

**Comment by duncansanderson** [comment]
Hey @kevinhinterlong, I'd like to work on this.

**Comment by kevinhinterlong** [comment]
Awesome @duncansanderson, thanks! Let me know if you need help
