### ISSUE TITLE
The directory table filter should handle clicks better

### ISSUE THREAD

**Issue by kevinhinterlong** [yahoo/navi#545]
**Describe the bug**
The directory table filter only opens if you click on the text or dropdown

**To Reproduce**
1. Go to https://yahoo.github.io/navi/#/directory/my-data
2. Click between 'All' and the dropdown arrow
3. Dropdown doesn't open/no cursor pointer

**Expected behavior**
The dropdown should open if you click in it.
Make the `selectedFileType` a span that fills the space so it can be clicked

**Screenshots**
![Screen Shot 2019-10-03 at 3 22 31 PM](https://user-images.githubusercontent.com/12093492/66161314-a636d080-e5f1-11e9-97bf-55cc7931382c.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome
 - Version 77

**Comment by shubhaemk** [comment]
I will do this!

**Comment by kevinhinterlong** [comment]
Thanks @shubhaemk! Let me know if you need any help with this

**Comment by shubhaemk** [comment]
Sorry, It took so long, ember seems overwhelming. Also, I made spelling mistake in  reference commit.

**Comment by kevinhinterlong** [comment]
No problem, thanks for the PR! Yea ember makes a lot of assumptions, so it's a little harder to get started, but much easier once you get to know it. 

No worries about the commit message, all the commits from your PR get squashed into 1 that we can rename if needed.

**Comment by shubhaemk** [comment]
Thanks!  Also, how should i incorporate changes suggested by you and other members?  A different commit?

**Comment by kevinhinterlong** [comment]
Yup, just push a new commit to your branch!

**Comment by shubhaemk** [comment]
Thanks, I did that! 🙌
