### ISSUE TITLE
Favorite Item should have gold outline on hover

### ISSUE THREAD

**Issue by kevinhinterlong** [yahoo/navi#547]
**Description**
It would be nice to see some transition on the star when we hover

**To Reproduce**
1. Go to https://yahoo.github.io/navi/#/reports/1/view
2. Hover on the star button
3. The color is still dark gray

**Expected behavior**
The star outline should turn into the `@favorite-gold` color here https://github.com/yahoo/navi/blob/ca8bef67c77c11fe8519f9175c839d2bdd46b2bf/packages/reports/app/styles/navi-reports/components/favorite-item.less#L6

**Screenshots**
![Screen Shot 2019-10-03 at 4 44 52 PM](https://user-images.githubusercontent.com/12093492/66166515-257dd180-e5fd-11e9-8781-78b712afac22.png)

**Comment by directdetour** [comment]
I'd like to take a shot at this.

**Comment by kevinhinterlong** [comment]
Sounds good! Let me know if you need help

**Comment by directdetour** [comment]
I'm trying to create a PR from my forked repo, but it showing previous file changes from my last PR. is that normal?

![image](https://user-images.githubusercontent.com/16309528/66174642-1100ff80-e624-11e9-8112-a8c01ea8e621.png)

**Comment by kevinhinterlong** [comment]
Yea so what happened here was that the first two commits from your original PR were squashed into one, and then that was applied to the `master` branch of the `yahoo/navi` repo
![image](https://user-images.githubusercontent.com/12093492/66174974-4d7d2d00-e61d-11e9-8438-f4d10d32ccd7.png)

But in your repo, `directdetour/navi`, your `master` branch is separate from the `yahoo/navi` `master` branch so it doesn't know the PR got merged. There's different ways of updating your branch to stay in sync with ours, but since you've added on another commit we'll skip the updating part.

Essentially you'll have to 
1. [add a remote](https://help.github.com/en/articles/adding-a-remote) (just once) to our repo,
    ```bash
    git remote add upstream https://github.com/yahoo/navi.git
    ```
2.  [fetch the changes](https://help.github.com/en/articles/getting-changes-from-a-remote-repository) from our repo
    ```bash
    git fetch upstream
    ```
3.  [pull in](https://stackoverflow.com/questions/36540645/updating-local-master-with-remote-master) the changes
    > If you want to start fresh and throw away your changes (like after you merge a PR)
    ```bash
    git reset --hard upstream/master
    ```

It can get complicated if you try to work directly on `master` since every time we merge a PR it will add changes to our `master` and your `master` branch will be out of date. It might help to look into some git intro so you can make each pr from it's own branch and just keep your `master` branch in sync with ours

**Comment by directdetour** [comment]
my local fork seems messed up and I wasn't able to push to my forked repo. I ended up making the previous change (with extra spaces) and the latest commit using the github web UI. I guess I could use some tips, once my PR is merged, to rebase(?) my fork and start using branching properly.  
![image](https://user-images.githubusercontent.com/16309528/66225149-b8724680-e6a5-11e9-88b1-654a967a37ec.png)

**Comment by kevinhinterlong** [comment]
Oh yea it looks like you got stuck on part of our commit check (first it fixes up small style issues if it finds any in the files you changed, then it checks the format of your commit message to make sure it follows our standard). In this situation it doesn't like that `cleanup` starts lower cased

If you changed it to `Update: Cleanup spaces ...` then it would actually do the commit and you would be able to push it
