### ISSUE TITLE
Notification in schedule modal not going away if clicking the x. only on "close"

### ISSUE THREAD

**Issue by colemanProjects** [yahoo/navi#554]
**Describe the bug**
Notification in schedule modal not going away if clicking the x. only on "close"

**To Reproduce**
1. Go to a report and set up a schedule
2. Click on 'Save'
3. See the notification show up
4. Click on the 'x' at the top right
5. Click on the 'schedule' button for the same report
6. Notice that the notification still exists
7. Repeat step 5-6 as many times and with clicking away from the schedule modal
8. Now try Clicking on 'Close' and repeating step 5
9. Notice that the notification is gone

**Expected behavior**
The notification should have the same behavior on "close", clicking the 'x', and clicking away from the schedule modal. 

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by nchand** [comment]
Hello, 

Can you give a little more info regarding this issue? I'm not getting this issue on my side.
