### ISSUE TITLE
Upgrade to Ember Octane

### ISSUE THREAD

**Issue by ldkge** [yahoo/navi#597]
TODO 
- [x] #603 Upgrade App
- [x] #604 Upgrade Core
- [x] #605 Upgrade Dashboard
- [x] #606 Upgrade Data
- [x] #607 Upgrade Directory
- [x] #608 Upgrade Notifications
- [x] #609 Upgrade Reports
- [x] Upgrade Search

**Comment by balajimanoharan** [comment]
blocked on https://github.com/lytics/ember-data-model-fragments/issues/345

**Comment by jkusa** [comment]
@balajimanoharan does this block Octane or just ED 3.14?

**Comment by balajimanoharan** [comment]
> @balajimanoharan does this block Octane or just ED 3.14?

yes, we could keep ember-data fixed at 3.12 until the issue is resolved.
