### ISSUE TITLE
Inconsistent methods to fetch uri from config

### ISSUE THREAD

**Issue by balajimanoharan** [yahoo/navi#615]
Related to Addon: **Navi Data**

We have multiple ways within the addons to fetch the uri's from the config.
The metadata adapter looks at the first object in the array
https://github.com/yahoo/navi/blob/master/packages/data/addon/adapters/bard-metadata.js#L11

The facts adapter looks for a specific name if available to find the uri https://github.com/yahoo/navi/blob/master/packages/data/addon/adapters/bard-facts.js#L184

We should standardize the way the uri is fetched from the config.

**Comment by cythrawll** [comment]
This is a continuing part of multi data source refactor, it will be covered in the next PR for multi data source support as we are adding support for metadata
