### ISSUE TITLE
Model validation error when using Asset search provider while on a report/dashboard

### ISSUE THREAD

**Issue by ldkge** [yahoo/navi#764]
**Describe the bug**
Some model validation is failing when performing a `store.query()` call while on a report or a dahsboard page. This error doesn't appear when you initiate a query on a different page.

**To Reproduce**
1. Go to Navigate to a report or a dashboard
2. Click on start typing a query into the search bar
3. See error in the developer console

```
Uncaught Error: Assertion Failed: You attempted to update `[]` on `<dummy@model:bard-request/fragments/interval::ember1183:owner(null)>`, but it had already been used previously in the same computation.  Attempting to update a value after using it in a computation can cause logical errors, infinite revalidation bugs, and performance issues, and is not supported.
`[]` was first used:
- While rendering:
  ----------------
    this.model.request.validations.isTruelyValid
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by mattgraham1995** [comment]
Does this happen on master?

**Comment by ldkge** [comment]
@mattgraham1995 Yes, I just rebased my branch on top of master and the error messages persist.

**Comment by mattgraham1995** [comment]
No not on your branch. I mean if I checkout master, is this bug present?

**Comment by ldkge** [comment]
The search bar isn't on master yet, but I could write an acceptance test to test it.

**Comment by mattgraham1995** [comment]
Could you confirm this issue is present in master first? If it's only present on your branch that's in PR, the issue should be resolved before that PR is merged.

**Comment by ldkge** [comment]
creating an acceptance test for it is harder than I thought, I need to add a router to search to be able to visit a report, but either ways the error must be in master too since I didn’t modify the asset search provider in my pr
