### ISSUE TITLE
[Bard adapter] Request the finest grain `dateTime` column

### ISSUE THREAD

**Issue by jkusa** [yahoo/navi#954]
Ultimately, if we need to attach coarser grain fields to the response, we will need to request the finest grain.

_Originally posted by @jkusa in https://github.com/_render_node/MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkMjkyNDgxNzc3OnYy/pull_request_review_threads/discussion_

**Comment by kevinhinterlong** [comment]
Closing in favor of throwing an error for now
